[package]
name = "demos"
version = "0.1.0"
edition = "2021"

[dependencies]

[features]
real = []

[profile.dev]
opt-level = 1 # don't generate absolute garbage code

[profile.release]
codegen-units = 1
debug = true
lto = true
